name: ral-aptamer

channels:
  - conda-forge
  - pytorch
  - bioconda

dependencies:
  - python>=3.6
  - numpy
  - pytorch>=1.9.0
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
#  - rnasketch
#  - pip>=20.0.2
#  - pip:
#      - seqfold
